name: learn-github-actions
run-name: ${{ github.action }} is learning GitHub Actions
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t go-hello-world .
      - run: docker tag go-hello-world dung041197/go-hello-world:0.0.2
      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASS
      - run: docker push dung041197/go-hello-world:0.0.2
